// Types representing the JSON data generated by WilckeWebDeployer

export interface WWDConfig {
    logoText: string;
    logoImageUrl?: string; // Optional: If the user uploads an image logo instead of text
    heroTitle: string;
    heroSubtitle: string;
    contactEmail: string;
    socialLinks?: {
        instagram?: string;
        facebook?: string;
    };
}

export interface WWDEvent {
    id: string;
    title: string;
    date: string;
    time?: string;
    location?: string;
    excerpt?: string;
    imageUrl?: string;
    url: string;
}

export interface WWDNews {
    id: string;
    title: string;
    date: string;
    excerpt: string;
    imageUrl?: string;
    url: string;
}
